language: node_js

node_js:
  - "4.1"

before_script:
  - npm install

script:
  - ./node_modules/mocha/bin/mocha

after_success:
  "curl -H \"Content-Type: application/json" --data '{\"build\": true}' -X POST $DOCKER_HUB_URL"
